### ISSUE TITLE
Which is a proper way to re-use module inside other modules and keep types working?

### ISSUE THREAD

**Issue by chernikov-v** [spb-web/vuexok#1]
There might be several scenarios when you need to reuse some module as sub module with separate state? which is the best way?
There are two options in my mind:

use function to return singleton or new module and use it as separate module but not as sub-module
keep config in separate variable which breaks auto-completes inside this config, so probably there should be separate method to get config from module or specific type to use with plain object config variable

**Comment by chernikov-v** [comment]
There might be several scenarios when you need to reuse some module as sub module with separate state? which is the best way?

**Comment by spb-web** [comment]
A simple solution to this problem is to create a function that will return a new module.

```ts
// getMyModule.ts
export default function getMyModule<S extends object>(moduleName, state:S) {
  return createModule(store, modulename, {
    state: () => state 
  })
}

// firstModule.ts
import getMyModule from './getMyModule'

export default getMyModule('first', { ... })

// secondModule.ts
import getMyModule from './getMyModule'

export default getMyModule('second', { ... })
```
Creating a method to get configuration from a module doesn't seem like a good idea.

**Comment by spb-web** [comment]
@chernikov-v Is your problem solved?
