### ISSUE TITLE
TypeError with Vue 3

### ISSUE THREAD

**Issue by mblackritter** [spb-web/vuexok#2]
Hi Vyacheslav,

thanks for the hint over at [Vuex-Typescript](https://github.com/istrib/vuex-typescript/issues/24#issuecomment-719996060), because I was just looking for the right Vuex modularization and typing package, so this must be the best "bujaka jaka jak"-surprise I coincidentally came by this year! 🥳🎉

It directly felt right, very right, and after implementing it (but see below), checking a few other solutions, and reconfirming myself how messy module management (rootThis, rootThat, ...) still becomes even with latest Vuex 4, I'm convinced that your way is what Vuex itself should be doing - perfect! 😻

But does it really already [support Vue 3](https://github.com/spb-web/vuexok#features)? 🤔

Because after transforming my store into Vuexok magic, and in frenetic expectations of a new level of store, all I could get from it was the following, which makes me guess I somehow missed the Vue 3 flag/option/package. 🙃

`TypeError: Object is not a constructor (evaluating 'new Vue__default['default']()')`

Tested it with plain Vue 3 CLI and Vite - same result.

Btw., what's the story to the name of `Vuexok`, as maybe `Vuexnov` could make you even more a well deserved legend! 😹💦

**Comment by OmgImAlexis** [comment]
@mblackritter you'll just need to wait for the next release as updating to the current GitHub code fixes the issue.

This was fixed by https://github.com/spb-web/vuexok/commit/1dbed61f9ffeceff7933a3473ac0fca31db44dc1

**Comment by OmgImAlexis** [comment]
@spb-web any chance on a new release?

**Comment by spb-web** [comment]
@OmgImAlexis @mblackritter 
Hi. Release coming soon in short time

**Comment by spb-web** [comment]
Fix released

**Comment by spb-web** [comment]
Fix released

**Comment by spb-web** [comment]
@mblackritter Problem solved? May I close the issue?
